name: Test with SwiftWasm

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: swiftwasm/swiftwasm-action@v5.7
        with:
          shell-action: carton test
